export const NOTE_CONTENT_CHANGED = "NOTE_CONTENT_CHANGED";

export const SAVE_NOTE_BUTTON_CLICKED = "SAVE_NOTE_BUTTON_CLICKED";

export const EDIT_NOTE_BUTTON_CLICKED = "EDIT_NOTE_BUTTON_CLICKED";

export const CANCEL_EDIT_NOTE_BUTTON_CLICKED =
  "CANCEL_EDIT_NOTE_BUTTON_CLICKED";
